blue green deployment strategy

diff --git a/.github/workflows/prod-deploy.yml b/.github/workflows/prod-deploy.yml
--- a/.github/workflows/prod-deploy.yml
+++ b/.github/workflows/prod-deploy.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow that is manually triggered
 
-name: Deploy to Production
+name: Blue - Green Deployment
 
 # Controls when the action will run. Workflow runs when manually triggered using the UI
 # or API.
@@ -8,6 +8,17 @@ on:
   workflow_dispatch:
     # Inputs the workflow accepts.
     inputs:
+      color:
+        description: 'Deployment type blue/green'
+        # Default value if no value is explicitly provided
+        default: 'green'
+        # Input has to be provided for the workflow to run
+        required: false
+        # The data type of the input
+        type: choice
+        options:
+          - blue
+          - green
       tag:
         # Friendly description to be shown in the UI instead of 'name'
         description: 'Deploy Version'
@@ -22,7 +33,6 @@ env:
   IMAGE: api-app
   GKE_CLUSTER: prod-cluster-iit    
   GKE_ZONE: us-central1
-  DEPLOYMENT_NAME: api-app
   CONTAINER: api-app
   REPO: us-central1-docker.pkg.dev/iit-cc/iit-cc 
 
@@ -48,11 +58,31 @@ jobs:
           location: ${{ env.GKE_ZONE }}
 
       # Deploy the Docker image to the GKE cluster
-      - name: Deploy to PROD
-        run: |-
-          # replacing the image name in the k8s template
-          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER=$REPO/api-app:'${{ inputs.tag }}'
-          kubectl rollout status deployment/$DEPLOYMENT_NAME
-          kubectl get services -o wide
+      - name: Deploy Blue/Green to Kubernetes
+        run: |
+          # Determine which color to deploy based on input color
+          if [ "${{ github.event.inputs.color }}" == blue ]; then
+            kubectl apply -f deployments/api-blue.yaml
+            # Enforce Application version
+            kubectl set image deployment/api-app-blue $CONTAINER=$REPO/api-app:'${{ inputs.tag }}'
+            kubectl rollout status deployment/api-app-blue
+          elif [ "${{ github.event.inputs.color }}" == green ]; then
+            kubectl apply -f deployments/api-green.yaml
+            # Enforce Application version
+            kubectl set image deployment/api-app-green $CONTAINER=$REPO/api-app:'${{ inputs.tag }}'
+            kubectl rollout status deployment/api-app-green
+          else
+            echo "Invalid color provided. Please provide 'blue' or 'green'."
+            exit 1
+          fi
+
+      - name: Update Ingress for Traffic Switching
+        if: success()
+        run: |
+          if [ "${{ github.event.inputs.color }}" == blue ]; then
+            kubectl apply -f deployments/ingress-blue.yaml
+          else
+            kubectl apply -f deployments/ingress-green.yaml
+          fi
           
     
